version: 1
providers:
    openai:
        api_key: ${OPENAI_TOKEN}
context:
    diff_token_limit: 8000
    overflow_strategy: trim
    per_file_token_cap: 2000
policy:
    min_severity_to_comment: info
    max_comments: 10
    allow_suggested_fixes: true
    redact_secrets: true
vcs:
    platform: github
    repository: raffaelecarelle/ai-code-review-bot
    access_token: ${CI_GITHUB_TOKEN}
excludes:
    - .github/**/*
    - .aicodereview.*
    - docs/**/*
    - .phpunit.result.cache