version: 1
providers:
  # Use 'mock' by default for safe, deterministic runs (no network calls)
  default: mock
context:
  diff_token_limit: 8000
  overflow_strategy: trim
  per_file_token_cap: 2000
policy:
  min_severity_to_comment: info
  max_comments: 50
  allow_suggested_fixes: true
  redact_secrets: true
guidelines_file: null
vcs:
  # Choose which platform to use when computing diffs via git and posting comments
  # Allowed values: github | gitlab | bitbucket
  platform: null
  
  # Repository identifier: "owner/repo" (GitHub), "namespace/project" (GitLab), "workspace/repo" (Bitbucket)
  repository: null
  # Authentication token (falls back to env vars: AICR_TOKEN, then platform-specific tokens)
  token: null
  # API base URL (defaults to platform standard, override for self-hosted instances)
  api_base: null
  # HTTP timeout in seconds
  timeout: 30
prompts:
  # Optional: append additional instructions to the LLM prompts
  # Accepts a string or a list of strings for system_append and user_append
  system_append: null
  user_append: []
  extra: []
