version: 1
providers:
    openai:
        api_key: ${CI_OPENAI_TOKEN}
context:
    diff_token_limit: 6000
    overflow_strategy: compress
    per_file_token_cap: 1500
    enable_semantic_chunking: true
    enable_diff_compression: true
policy:
    min_severity_to_comment: warning
    max_comments: 25
    consolidate_similar_findings: true
    max_findings_per_file: 3
    redact_secrets: true
    severity_limits:
        error: 10
        warning: 10
vcs:
    platform: github
    repository: raffaelecarelle/ai-code-review-bot
    access_token: ${GITHUB_TOKEN}
excludes:
    - .github/**/*
    - .aicodereview.*
    - docs/**/*
    - .phpunit.result.cache
    - "*.md"
    - '*.html'