name: CI

on:
    push:
    pull_request:

jobs:
    qa:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3', '8.4', '8.5' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: xdebug
                    tools: composer:v2

            -   name: Validate composer.json
                run: composer validate --no-check-all --no-interaction

            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: |
                        ~/.cache/composer/files
                        ~/.composer/cache/files
                    key: composer-${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        composer-${{ runner.os }}-${{ matrix.php }}-
                        composer-${{ runner.os }}-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-interaction

            -   name: Coding standards (php-cs-fixer dry-run)
                run: composer cs:check

            -   name: Rector (dry-run)
                run: composer rector:dry

            -   name: Static analysis (phpstan)
                run: composer analyse

            -   name: Tests with coverage (phpunit)
                run: mkdir -p build/coverage && composer tests -- --coverage-clover=build/coverage/clover.xml --coverage-text

            -   name: Upload coverage artifact
                uses: actions/upload-artifact@v4
                with:
                    name: coverage-php${{ matrix.php }}
                    path: build/coverage

            -   name: AI Code Review
                if: github.event_name == 'pull_request' && matrix.php == '8.3'
                env:
                    CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
                    CI_OPENAI_TOKEN: ${{ secrets.CI_OPENAI_TOKEN }}
                run: |
                    git config --global --add safe.directory /app
                    git config --global user.name "AI Code Review Bot"
                    git fetch --all --prune
                    git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} || true
                    git fetch origin ${{ github.head_ref }}:${{ github.head_ref }} || true

                    # Only run AI review on one PHP version to avoid duplicate comments
                    php bin/aicr --id=${{ github.event.pull_request.number }} --config=.aicodereview.yml --comment --output=markdown
